kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: <NAMESPACE>
  name: ecr-token-helper
rules:
  - apiGroups: [""]
    resources:
      - secrets
      - serviceaccounts
      - serviceaccounts/token
    verbs:
      - 'delete'
      - 'create'
      - 'patch'
      - 'get'
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ecr-token-helper
  namespace: <NAMESPACE>
subjects:
  - kind: ServiceAccount
    name: sa-ecr-token-helper
    namespace: <NAMESPACE>
roleRef:
  kind: Role
  name: ecr-token-helper
  apiGroup: ""
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-ecr-token-helper
  namespace: <NAMESPACE>
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: ecr-token-helper
  namespace: <NAMESPACE>
spec:
  schedule: '0 */6 * * *'
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 0
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: sa-ecr-token-helper
          containers:
            - command:
                - /bin/sh
                - -c
                - |-
                  TOKEN=`aws ecr get-login-password --region ${REGION} | cut -d' ' -f6`
                  kubectl delete secret -n <NAMESPACE> --ignore-not-found $SECRET_NAME
                  kubectl create secret -n <NAMESPACE> docker-registry $SECRET_NAME \
                    --docker-server=$ECR_REPOSITORY \
                    --docker-username=AWS \
                    --docker-password=$TOKEN \
                    --namespace=<NAMESPACE>
                  kubectl patch serviceaccount default-editor -p '{"imagePullSecrets":[{"name":"'$SECRET_NAME'"}]}' -n <NAMESPACE>
              env:
                - name: AWS_ACCESS_KEY_ID
                  value: <AWS_ACCESS_KEY_ID>
                - name: AWS_SECRET_ACCESS_KEY
                  value: <AWS_SECRET_ACCESS_KEY>
                - name: ACCOUNT
                  value: <ACCOUNT_ID>
                - name: SECRET_NAME
                  value: "regcred"
                - name: REGION
                  value: "ap-northeast-2"
                - name: ECR_REPOSITORY
                  value: <ECR_REPOSITORY>
              image: gtsopour/awscli-kubectl:latest
              imagePullPolicy: IfNotPresent
              name: ecr-token-helper
          restartPolicy: Never
